# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RealignRaster
                                 A QGIS plugin
 This plugin allows you to easily realign any multi-band raster image to a reference raster, ensuring accurate spatial alignment.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-22
        copyright            : (C) 2023 by shailesh-stha
        email                : shailesh.shrestha@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RealignRaster class from file RealignRaster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .realign_raster import RealignRaster
    return RealignRaster(iface)
